# Generated by Django 5.0.14 on 2026-08-06 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_paper_ingestion_job'),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('supporting', 'Supporting'), ('contradicting', 'Contradicting'), ('mentioning', 'Mentioning'), ('unanalyzed', 'Unanalyzed')], default='unanalyzed', max_length=16)),
                ('context', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cited_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='papers.paper')),
                ('citing_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='papers.paper')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_relations', to='api.researchproject')),
            ],
        ),
        migrations.AddConstraint(
            model_name='paperrelation',
            constraint=models.UniqueConstraint(fields=('project', 'citing_paper', 'cited_paper'), name='uniq_paper_relation'),
        ),
    ]
