# Generated by Django 5.0.14 on 2026-08-11 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_paper_relation_context'),
        ('papers', '0001_initial'),
        ('rag', '0004_paper_index_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperingestionjob',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paperingestionjob',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='paperingestionjob',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paperingestionjob',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='paperingestionjob',
            name='index_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_jobs', to='rag.paperindexversion'),
        ),
        migrations.AddField(
            model_name='paperingestionjob',
            name='retryable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paperingestionjob',
            name='source_kind',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='paperingestionjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('parsing', 'Parsing'), ('embedding', 'Embedding'), ('committing', 'Committing'), ('embedded', 'Embedded'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='paperingestionjob',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('project', 'paper', 'idempotency_key'), name='uniq_ingestion_project_paper_key'),
        ),
    ]
