# Generated by Django 5.0.14 on 2026-08-13 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_paper_ingestion_job_v2'),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorkflowDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('unavailable', 'Unavailable')], default='pending', max_length=16)),
                ('terminal_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='paperingestionjob',
            name='terminal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrun',
            name='draft_output',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectrun',
            name='first_rag_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrun',
            name='last_ingestion_terminal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrun',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrun',
            name='owner_token',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='projectrun',
            name='resume_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectrun',
            name='workflow_phase',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='projectrunevent',
            name='dedupe_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='reportversion',
            name='source_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_report', to='api.projectrun'),
        ),
        migrations.AlterField(
            model_name='projectrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting_ingestion', 'Waiting Ingestion'), ('done', 'Done'), ('partial', 'Partial'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='projectrunevent',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('run', 'dedupe_key'), name='uniq_event_run_dedupe_key'),
        ),
        migrations.AddField(
            model_name='projectworkflowdependency',
            name='ingestion_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_dependencies', to='api.paperingestionjob'),
        ),
        migrations.AddField(
            model_name='projectworkflowdependency',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_dependencies', to='papers.paper'),
        ),
        migrations.AddField(
            model_name='projectworkflowdependency',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_dependencies', to='api.projectrun'),
        ),
        migrations.AddIndex(
            model_name='projectworkflowdependency',
            index=models.Index(fields=['run', 'status'], name='api_pwdep_run_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectworkflowdependency',
            constraint=models.UniqueConstraint(fields=('run', 'paper'), name='uniq_workflow_dep_run_paper'),
        ),
    ]
