# Generated by Django 5.0.14 on 2026-08-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_workflow_lifecycle_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrun',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrun',
            name='waiting_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
