"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# 加载 .env（DEEPSEEK_API_KEY 等本地配置；不提交到 git）
load_dotenv(Path(__file__).resolve().parent.parent / ".env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Local dev falls back to a fixed insecure key; production MUST set
# DJANGO_SECRET_KEY (see .env.example).
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or "django-insecure-tv%4hcyp(7*=vmxe!1&2(!hio-g^2d9bzad=p$zrvktht2r!_6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0").split(",")
    if host.strip()
]

IS_TESTING = "test" in sys.argv
# GPT v5: force HF/transformers offline in test mode as a second layer of network
# protection (first layer is fake provider + mocked datasources/Docling).
if IS_TESTING:
    os.environ.setdefault("HF_HUB_OFFLINE", "1")
    os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")
# In test mode, default the live LLM OFF so deterministic eval tests never
# burn real DeepSeek quota. An explicit PAPERLENS_TEST_LIVE_LLM=1 can opt back in.
PROJECT_CHAT_LIVE_LLM = (
    (os.environ.get("PAPERLENS_TEST_LIVE_LLM") == "1")
    if IS_TESTING
    else (os.environ.get("PAPERLENS_PROJECT_CHAT_LIVE_LLM", "1") == "1")
)


# Application definition
# Daphne 必须是第一项：让 runserver 以 ASGI 模式运行，为后续 SSE 流式端点铺路
# （WSGI 会缓冲响应体，导致 SSE 失效——这是地基验证外的已知工程事实）
INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'papers',
    'datasources',
    'agent',
    'rag',
    'citation',
    'api',
    'realtime',
    'eval',
]

# ASGI application（Daphne 接管 runserver 的关键）
ASGI_APPLICATION = 'config.asgi.application'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 必须在 CommonMiddleware 之前
    'config.middleware.RequestIDMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS：允许 Vue dev server (localhost:5173) 跨域访问 API
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
]

ROOT_URLCONF = 'config.urls'

# DRF：演示项目，API 免认证免 CSRF（本地单用户）
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# Docker/demo deployments use PostgreSQL + pgvector via DATABASE_URL. A SQLite
# fallback is kept for fast local tests when Docker is not available.
DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=int(os.environ.get("DATABASE_CONN_MAX_AGE", "60")),
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_ROOT = Path(os.environ.get("DJANGO_MEDIA_ROOT", BASE_DIR / "media"))
MEDIA_URL = os.environ.get("DJANGO_MEDIA_URL", "/media/")

# GPT v5: custom test runner with socket-level network guard for offline suite.
TEST_RUNNER = "config.test_runner.GuardedTestRunner"

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/1")
CELERY_TASK_ALWAYS_EAGER = os.environ.get("CELERY_TASK_ALWAYS_EAGER", "0") == "1" or IS_TESTING
CELERY_TASK_EAGER_PROPAGATES = True

PAPERLENS_EMBEDDING_PROVIDER = os.environ.get("PAPERLENS_EMBEDDING_PROVIDER", "bge-m3")
PAPERLENS_EMBEDDING_MODEL = os.environ.get("PAPERLENS_EMBEDDING_MODEL", "BAAI/bge-m3")
PAPERLENS_EMBEDDING_DIM = int(os.environ.get("PAPERLENS_EMBEDDING_DIM", "1024"))
# 测试环境强制 fake provider，避免下载真实 BGE-M3/Qwen3 模型和访问 HuggingFace。
# 即使 .env 设了 bge-m3，测试也用 fake（除非显式 PAPERLENS_TEST_REAL_EMBEDDING=1）。
if IS_TESTING and os.environ.get("PAPERLENS_TEST_REAL_EMBEDDING") != "1":
    PAPERLENS_EMBEDDING_PROVIDER = "fake"
PAPERLENS_EMBEDDING_VERSION = os.environ.get(
    "PAPERLENS_EMBEDDING_VERSION",
    f"{PAPERLENS_EMBEDDING_MODEL}:dim{PAPERLENS_EMBEDDING_DIM}:norm",
)
PAPERLENS_RAG_DENSE_K = int(os.environ.get("PAPERLENS_RAG_DENSE_K", "20"))
PAPERLENS_RAG_LEXICAL_K = int(os.environ.get("PAPERLENS_RAG_LEXICAL_K", "20"))
PAPERLENS_RAG_FINAL_K = int(os.environ.get("PAPERLENS_RAG_FINAL_K", "8"))
PAPERLENS_RAG_RRF_K = int(os.environ.get("PAPERLENS_RAG_RRF_K", "60"))

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOG_LEVEL = os.environ.get("PAPERLENS_LOG_LEVEL", "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_context": {
            "()": "config.logging_context.RequestContextFilter",
        },
    },
    "formatters": {
        "json": {
            "()": "config.logging_context.JsonLogFormatter",
        },
        "console": {
            "format": "%(levelname)s %(name)s event=%(event)s request=%(request_id)s task=%(task_id)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "console",
            "filters": ["request_context"],
            "level": LOG_LEVEL,
        },
        "app_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "paperlens.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "encoding": "utf-8",
            "formatter": "json",
            "filters": ["request_context"],
            "level": LOG_LEVEL,
        },
        "error_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "errors.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "encoding": "utf-8",
            "formatter": "json",
            "filters": ["request_context"],
            "level": "ERROR",
        },
    },
    "root": {
        "handlers": ["console", "app_file", "error_file"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django.server": {
            "handlers": ["console", "app_file"],
            "level": "INFO",
            "propagate": False,
        },
        "paperlens.request": {
            "handlers": ["console", "app_file", "error_file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}


# 启动期配置就绪提示（仅一次，便于公开仓库用户快速定位问题）
import logging as _logging

_startup_logger = _logging.getLogger("paperlens.startup")
if not IS_TESTING:
    if not os.environ.get("DEEPSEEK_API_KEY", ""):
        _startup_logger.warning(
            "DEEPSEEK_API_KEY 未配置：服务可正常启动，但 Agent Chat / 报告生成 / "
            "RAG 重排等 LLM 功能将返回明确提示。请在 backend/.env 填入你的 "
            "DeepSeek API Key 后重启（参考 README 的 Configuration 章节）。"
        )
