# Generated by Django 5.0.14 on 2026-07-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasourceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=32)),
                ('qhash', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='datasourcecache',
            constraint=models.UniqueConstraint(fields=('source', 'qhash'), name='uniq_ds_cache'),
        ),
    ]
