# Generated by Django 5.0.14 on 2026-07-30 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('openalex_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=256)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openalex_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('s2_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('doi', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('arxiv_id', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('title', models.TextField()),
                ('abstract', models.TextField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('citation_count', models.IntegerField(default=0)),
                ('referenced_works', models.JSONField(blank=True, default=list)),
                ('pdf_url', models.URLField(blank=True, max_length=512, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('venue_type', models.CharField(blank=True, max_length=64)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('openalex_id',), name='uniq_author_openalex'),
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='papers', to='papers.author'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('name',), name='uniq_venue_name'),
        ),
        migrations.AddField(
            model_name='paper',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='papers.venue'),
        ),
        migrations.AddConstraint(
            model_name='paper',
            constraint=models.UniqueConstraint(fields=('doi',), name='uniq_paper_doi'),
        ),
        migrations.AddConstraint(
            model_name='paper',
            constraint=models.UniqueConstraint(fields=('arxiv_id',), name='uniq_paper_arxiv'),
        ),
        migrations.AddConstraint(
            model_name='paper',
            constraint=models.UniqueConstraint(fields=('openalex_id',), name='uniq_paper_openalex'),
        ),
    ]
