# Generated by Django 5.0.14 on 2026-07-30 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(max_length=256)),
                ('chunk_index', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(default=list)),
                ('citation_key', models.CharField(db_index=True, max_length=32)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='papers.paper')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('summary', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('citation_key', models.CharField(db_index=True, max_length=32)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='rag.text')),
            ],
        ),
        migrations.AddConstraint(
            model_name='text',
            constraint=models.UniqueConstraint(fields=('paper', 'chunk_index'), name='uniq_text_paper_chunk'),
        ),
    ]
