# Generated by Django 5.0.14 on 2026-08-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_hybrid_rag_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='sparse_weights',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
